/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeliveryStatus {
	_id: string;
	type: "DeliveryStatus";
	trackingId: string;
	tracking_number?: string;
	user_id: number;
	client?: string;
	destination_country_iso3?: null | string;
	courier?: string;
	details: {
		trackingId: string;
		deliveryStatus: string;
		matching: {
			checkpointId?: string;
			Message: string;
			DeliveryStatus: string;
			event_timestamp: string;
			scan_location?: string;
			status_details: string;
			_internal_timestamp: number;
			Format?: {
				startDay: string;
				locale?: string;
				startTime?: string;
				endTime?: string;
				endDay?: string;
				[k: string]: unknown;
			};
			Specifics?: string;
			ParsedSpecifics?: {
				startDay: string;
				endDay: null | string;
				startTime?: null | string;
				endTime?: null | string;
				[k: string]: unknown;
			};
			IsInboundScan?: boolean;
			DeliveryLocation?: string;
			Exception?: string[];
			ScheduledCount?: number;
			NextAction?: string;
			shadowedMatching?: {
				Message: string;
				DeliveryStatus: string;
				DeliveryLocation?: string;
				event_timestamp: string;
				scan_location: string;
				status_details: string;
				ReturnDeliveryStatus?: string;
				[k: string]: unknown;
			};
			ReturnDeliveryStatus?: string;
			[k: string]: unknown;
		};
		latestFingerprint: string;
		_internal_timestamp: number;
		eventId: string;
		trigger: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			LocaleMessage?: boolean;
			Delay?: number;
			ActivateOrderPlaceholders?: boolean;
			Recipient: {
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				plTest?: boolean;
				courierContact?: boolean;
				theirs?: boolean | number | null;
				[k: string]: unknown;
			};
			Filter: string;
			deduplicationId: string;
			OncePerOrder?: boolean;
			FilterOnSendId?: string;
			OncePerTracking?: boolean;
			SendToUnsubscribed?: boolean;
			OncePerDeliveryInOrder?: boolean;
			DelayOfWorkingHours?: number;
			FilterOnSend?: {
				$and?: {
					"reporting.courier_dropoff_date"?: null;
					"reporting.in_transit_date"?: {
						$ne: null;
						[k: string]: unknown;
					};
					$or?: {
						[k: string]: unknown;
					}[];
					"reporting.delivery_date"?: null;
					[k: string]: unknown;
				}[];
				"reporting.delivery_date"?: null;
				[k: string]: unknown;
			};
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			OnlyWithSpecificsTime?: boolean;
			AllowedNextAction?: null | {
				PickUpReady: boolean;
				NewAttemptToday: boolean;
				NewAttemptNextDay: boolean;
				Empty: boolean;
				[k: string]: unknown;
			};
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null | string;
			PushNotification?: boolean;
			IsServiceNotice?: boolean;
			RecheckFilterId?: string;
			ShortenURLs?: boolean;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		reason?: string;
		[k: string]: unknown;
	};
	created: string;
	createdTs: number;
	__v: number;
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	delay?: number;
	[k: string]: unknown;
}
