/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Dispatch {
	_id: string;
	type: "Dispatch";
	trackingId: string;
	tracking_number: string;
	user_id: number;
	client?: string;
	destination_country_iso3?: string;
	courier: string;
	details: {
		trackingId: string;
		deliveryStatus: string;
		matching: {
			checkpointId: string;
			Message: string;
			DeliveryStatus: string;
			event_timestamp: string;
			status_details: string;
			IsInboundScan: boolean;
			_internal_timestamp: number;
			scan_location?: string;
			Format?: {
				startDay: string;
				startTime?: string;
				endTime?: string;
				locale?: string;
				endDay?: string;
				[k: string]: unknown;
			};
			Specifics?: string;
			ParsedSpecifics?: {
				startDay: string;
				endDay: null | string;
				startTime?: null | string;
				endTime?: null | string;
				[k: string]: unknown;
			};
			DeliveryLocation?: string;
			ScheduledCount?: number;
			ReturnDeliveryStatus?: string;
			Exception?: string[];
			[k: string]: unknown;
		};
		latestFingerprint: string;
		_internal_timestamp: number;
		eventId: string;
		trigger: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			Delay: number;
			Recipient: {
				theirs: number;
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				courierContact?: boolean;
				plTest?: boolean;
				[k: string]: unknown;
			};
			Filter: string;
			deduplicationId: string;
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			OnlyWithSpecificsTime?: boolean;
			AllowedNextAction?: null;
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null;
			OncePerTracking?: boolean;
			PushNotification?: boolean;
			SendToUnsubscribed?: boolean;
			IsServiceNotice?: boolean;
			FilterOnSendId?: string;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		[k: string]: unknown;
	};
	created: string;
	createdTs: number;
	__v: number;
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	delay?: number;
	[k: string]: unknown;
}
