/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LeadTimeExceeded {
	_id: string;
	type: "LeadTimeExceeded";
	trackingId: string;
	tracking_number: string;
	user_id: number;
	client?: string;
	destination_country_iso3: string;
	courier: string;
	details: {
		eventId: string;
		[k: string]: unknown;
	};
	created: string;
	createdTs: number;
	__v: number;
	[k: string]: unknown;
}
