/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrderCreated {
	_id: string;
	type: "OrderCreated";
	trackingId: string;
	user_id: number;
	destination_country_iso3?: null | string;
	courier?: string;
	details: {
		_internal_timestamp: number;
		eventId: string;
		trackingId?: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			OncePerDeliveryInOrder?: boolean;
			DelayByReference?: {
				Key: string;
				Offset: number;
				[k: string]: unknown;
			};
			Recipient: {
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				plTest?: boolean;
				theirs?: boolean | number | null;
				courierContact?: boolean;
				[k: string]: unknown;
			};
			Filter: string;
			FilterOnSendId?: string;
			FilterOnSend?: {
				$and: {
					"reporting.delivery_date"?: null;
					$and?: {
						tracking_number?: {
							$eq: null;
							[k: string]: unknown;
						};
						"delivery_info.cancelled"?: {
							$ne: boolean;
							[k: string]: unknown;
						};
						"delivery_info.customFields.orderWasConsolidated"?: {
							$ne: boolean;
							[k: string]: unknown;
						};
						"reporting.in_transit_date"?: null;
						[k: string]: unknown;
					}[];
					"reporting.contactedWithMessages"?:
						| unknown[]
						| {
								$not: {
									$regex: string;
									[k: string]: unknown;
								};
								[k: string]: unknown;
						  };
					"reporting.in_transit_date"?: {
						$eq: null;
						[k: string]: unknown;
					};
					"delivery_info.articlesOpen"?: {
						$size: number;
						[k: string]: unknown;
					};
					"delivery_info.cancelled"?: {
						$ne: boolean;
						[k: string]: unknown;
					};
					"delivery_info.customFields.isBOPIS"?: {
						$nin: (boolean | string)[];
						[k: string]: unknown;
					};
					"delivery_info.courierServiceLevel"?: {
						$nin: string[];
						[k: string]: unknown;
					};
					tracking_number?: {
						$eq: null;
						[k: string]: unknown;
					};
					"delivery_info.customFields.orderWasConsolidated"?: {
						$ne: boolean;
						[k: string]: unknown;
					};
					$not?: {
						courier: string;
						[k: string]: unknown;
					};
					"delivery_info.customFields.deliveryMode"?: {
						$in: string[];
						[k: string]: unknown;
					};
					"delivery_info.customFields.donation_only"?: {
						$eq: boolean;
						[k: string]: unknown;
					};
					"delivery_info.customFields.channel"?: {
						$ne: string;
						[k: string]: unknown;
					};
					"delivery_info.client"?: {
						$in?: string[];
						$nin?: string[];
						[k: string]: unknown;
					};
					"delivery_info.orderNo"?: {
						$nin: string[];
						[k: string]: unknown;
					};
					"delivery_info.customFields.payment"?: {
						$nin: string[];
						[k: string]: unknown;
					};
					courier?: {
						$nin?: string[];
						$eq?: null;
						$ne?: null;
						[k: string]: unknown;
					};
					"delivery_info.email"?: {
						$ne: null;
						[k: string]: unknown;
					};
					[k: string]: unknown;
				}[];
				[k: string]: unknown;
			};
			deduplicationId: string;
			LocaleMessage?: boolean;
			DelayByOffsetReference?: {
				Key: string;
				TimeUnitInValueField: string;
				ConsiderWorkingHours: boolean;
				[k: string]: unknown;
			};
			ActivateOrderPlaceholders?: boolean;
			Delay?: number;
			OncePerOrder?: boolean;
			RecheckFilterId?: string;
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			OnlyWithSpecificsTime?: boolean;
			AllowedNextAction?: null;
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null;
			OncePerTracking?: boolean;
			PushNotification?: boolean;
			SendToUnsubscribed?: boolean;
			IsServiceNotice?: boolean;
			DelayOfWorkingHours?: number;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		trigger?: string;
		[k: string]: unknown;
	};
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	created: string;
	createdTs: number;
	__v: number;
	client?: string;
	delay?: number;
	tracking_number?: string;
	[k: string]: unknown;
}
