/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrderUpdated {
	_id: string;
	type: "OrderUpdated";
	trackingId: string;
	user_id: number;
	client?: string;
	destination_country_iso3?: string;
	details: {
		_internal_timestamp: number;
		eventId: string;
		trigger?: string;
		trackingId?: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			IsServiceNotice?: boolean;
			Recipient: {
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				plTest?: boolean;
				theirs?: number;
				courierContact?: boolean;
				[k: string]: unknown;
			};
			OncePerOrder?: boolean;
			LocaleMessage?: boolean;
			Delay?: number;
			Filter: string;
			deduplicationId: string;
			FilterOnSendId?: string;
			ActivateOrderPlaceholders?: boolean;
			DelayOfWorkingHours?: number;
			FilterOnSend?: {
				$and: {
					$not?: {
						"reporting.contactedWithMessages"?: {
							$regex: string;
							[k: string]: unknown;
						};
						"delivery_info.customFields.Centiro-Shipment_WOCancelledComp"?: {
							$ne: null;
							[k: string]: unknown;
						};
						[k: string]: unknown;
					};
					checkpoints?: unknown[];
					$or?: {
						"delivery_info.customFields.Centiro-Shipment_WODepComp"?: {
							$ne: null;
							[k: string]: unknown;
						};
						"delivery_info.customFields.Centiro-Shipment_WOUpdatedComp"?: {
							$ne: null;
							[k: string]: unknown;
						};
						"delivery_info.customFields.Centiro-Shipment_SCR"?: {
							$ne: null;
							[k: string]: unknown;
						};
						"delivery_info.customFields.Centiro-Shipment_CloseTripPickResult"?: {
							$ne: null;
							[k: string]: unknown;
						};
						"delivery_info.customFields.Centiro-Shipment_Status40"?: {
							$ne: null;
							[k: string]: unknown;
						};
						[k: string]: unknown;
					}[];
					$and?: {
						"delivery_info.customFields.cancelledByKafka"?: boolean;
						"delivery_info.customFields.cancelReason"?: {
							$in: string[];
							[k: string]: unknown;
						};
						[k: string]: unknown;
					}[];
					"reporting.returned"?: boolean;
					"delivery_info.return"?: boolean;
					[k: string]: unknown;
				}[];
				[k: string]: unknown;
			};
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			OnlyWithSpecificsTime?: boolean;
			AllowedNextAction?: null;
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null;
			OncePerTracking?: boolean;
			PushNotification?: boolean;
			SendToUnsubscribed?: boolean;
			RecheckFilterId?: string;
			DelayByReference?: {
				Key: string;
				Offset: number;
				[k: string]: unknown;
			};
			OncePerDeliveryInOrder?: boolean;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		[k: string]: unknown;
	};
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	delay?: number;
	created: string;
	createdTs: number;
	__v: number;
	tracking_number?: string;
	courier?: string;
	[k: string]: unknown;
}
