/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PickupReady {
	_id: string;
	type: "PickupReady";
	trackingId: string;
	tracking_number: string;
	user_id: number;
	client?: string;
	destination_country_iso3?: string;
	courier: string;
	details: {
		trackingId: string;
		deliveryStatus: string;
		matching: {
			checkpointId: string;
			Message: string;
			DeliveryStatus: string;
			DeliveryLocation: string;
			Specifics?: string;
			event_timestamp: string;
			status_details: string;
			_internal_timestamp: number;
			scan_location?: string;
			IsInboundScan?: boolean;
			[k: string]: unknown;
		};
		latestFingerprint: string;
		_internal_timestamp: number;
		eventId: string;
		trigger: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			OncePerTracking?: boolean;
			LocaleMessage?: boolean;
			Delay?: number;
			Recipient: {
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				plTest?: boolean;
				courierContact?: boolean;
				theirs?: boolean | number | null;
				[k: string]: unknown;
			};
			Filter: string;
			deduplicationId: string;
			PushNotification?: boolean;
			OncePerOrder?: boolean;
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			FilterOnSend?: {
				$and?: {
					"reporting.returned"?: {
						$ne: boolean;
						[k: string]: unknown;
					};
					"delivery_info.return"?: {
						$ne: boolean;
						[k: string]: unknown;
					};
					"reporting.delivery_date"?: null;
					[k: string]: unknown;
				}[];
				"reporting.delivery_date"?: null;
				[k: string]: unknown;
			};
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			OnlyWithSpecificsTime?: boolean;
			AllowedNextAction?: null;
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null;
			SendToUnsubscribed?: boolean;
			IsServiceNotice?: boolean;
			FilterOnSendId?: string;
			ActivateOrderPlaceholders?: boolean;
			RecheckFilterId?: string;
			DelayOfWorkingHours?: number;
			OncePerDeliveryInOrder?: boolean;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		[k: string]: unknown;
	};
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	delay?: number;
	created: string;
	createdTs: number;
	__v: number;
	[k: string]: unknown;
}
