/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Scheduled {
	_id: string;
	type: "Scheduled";
	trackingId: string;
	tracking_number: string;
	user_id: number;
	client?: string;
	destination_country_iso3?: null | string;
	courier: string;
	details: {
		trackingId: string;
		deliveryStatus: string;
		matching: {
			checkpointId: string;
			Message: string;
			DeliveryStatus: string;
			Format: {
				startDay: string;
				endTime?: string;
				locale?: string;
				startTime?: string;
				endDay?: string;
				[k: string]: unknown;
			};
			Specifics: string;
			ParsedSpecifics: {
				startDay: string;
				endDay: null | string;
				endTime?: null | string;
				startTime?: null | string;
				[k: string]: unknown;
			};
			event_timestamp: string;
			status_details: string;
			_internal_timestamp: number;
			IsInboundScan?: boolean;
			ScheduledCount?: number;
			scan_location?: string;
			shadowedMatching?: {
				Message: string;
				DeliveryStatus: string;
				ReturnDeliveryStatus?: string;
				event_timestamp: string;
				scan_location: string;
				status_details: string;
				DeliveryLocation?: string;
				Specifics?: string;
				[k: string]: unknown;
			};
			[k: string]: unknown;
		};
		latestFingerprint: string;
		_internal_timestamp: number;
		eventId: string;
		trigger: string;
		message?: {
			Trigger: string;
			Channel: string;
			Message: string;
			LocaleMessage?: boolean;
			Delay: number;
			Recipient: {
				customer?: boolean;
				support?: boolean;
				test?: boolean;
				plTest?: boolean;
				courierContact?: boolean;
				theirs?: boolean | number | null;
				[k: string]: unknown;
			};
			Filter: string;
			deduplicationId: string;
			OncePerDeliveryInOrder?: boolean;
			ActivateOrderPlaceholders?: boolean;
			FilterOnSendId?: string;
			FilterOnSend?: {
				$and: {
					[k: string]: unknown;
				}[];
				[k: string]: unknown;
			};
			OnlyWithSpecificsTime?: boolean;
			Account?: number;
			Id?: number;
			SlotType?: string;
			EventTypes?: string;
			Name?: string;
			SendOnlyIfMultipleTracking?: boolean;
			SendOnlyIfSingleTracking?: boolean;
			OnlyWithSpecifics?: boolean;
			AllowedNextAction?: null;
			CompletelyDelivered?: boolean;
			ShortenUrls?: boolean;
			OnlyOncePer?: null;
			OncePerTracking?: boolean;
			PushNotification?: boolean;
			SendToUnsubscribed?: boolean;
			IsServiceNotice?: boolean;
			OncePerOrder?: boolean;
			[k: string]: unknown;
		};
		delay?: number;
		event?: string;
		user_id?: number;
		[k: string]: unknown;
	};
	filter?: string;
	trigger?: string;
	channel?: string;
	message?: string;
	delay?: number;
	created: string;
	createdTs: number;
	__v: number;
	[k: string]: unknown;
}
